name: CI
on: [push, pull_request]

jobs:
    run_tests:
      runs-on: [ubuntu-latest]
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Install Python
          uses: actions/setup-python@v1
          with:
            python-version: '3.8'
            architecture: 'x64'
        - name: Install requirements
          run: pip install -r requirements.txt
        - name: Run PyTest
          run: pytest