name: CI
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test_and_lint:
    name: Test and Lint
    runs-on: "ubuntu-latest"
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Update pip
      run: python -m pip install --upgrade pip
    - name: Install requirements
      run: python -m pip install -r requirements.txt
    - name: Install linters
      run: python -m pip install "pydocstyle<4.0.0" flake8 flake8-docstrings mypy
    - name: Run PyTest
      run: python -m pytest
    - name: Run Flake8
      run: python -m flake8
    - name: Run mypy
      run: python -m mypy src/

  check_code_formatting:
    name: Check code formatting with Black
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Update pip
      run: python -m pip install --upgrade pip
    - name: Install Black
      run: python -m pip install black==19.3b0
    - name: Run Black
      run: python -m black --config=black.toml --check .
