name: CI
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  run_tests:
    runs-on: "ubuntu-latest"
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Update pip
      run: pip install --upgrade pip
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Run PyTest
      run: python -m pytest